apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: trilio
  namespace: openshift-gitops
spec:
  destinations:
    - namespace: trilio-system
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
