apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: trilio-license
  namespace: trilio-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: trilio-license
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        key: "{{ `{{ .trilio_license_key }}` }}"
  data:
    - secretKey: trilio_license_key
      remoteRef:
        key: secret/global/trilio-license
        property: key
