apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trilio-license-job
  namespace: {{ .Values.trilio.namespace | default "trilio-system" }}
subjects:
  - kind: ServiceAccount
    name: trilio-license-job
    namespace: {{ .Values.trilio.namespace | default "trilio-system" }}
roleRef:
  kind: Role
  name: trilio-license-job
  apiGroup: rbac.authorization.k8s.io
